version: "3.6"
services:
  console:
    image: craftcms/cli:8.2-dev
    env_file: .env
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    depends_on:
      - mysql
    volumes:
      - .:/app
    command: php craft queue/listen
  web:
    image: craftcms/nginx:8.2-dev
    ports:
      - 8080:8080
      - 443:443
    env_file: .env
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    depends_on:
      - mysql
    volumes:
      - .:/app
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: SecretPassword
      MYSQL_DATABASE: semplicesoions_craft
      MYSQL_USER: semplicesoions_craft
      MYSQL_PASSWORD: SUjqPImdg0V^&U42
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 3
volumes:
  db_data:
