color: violet
fieldLayouts:
  1ee12b89-a0c3-4030-b17b-67e3d7e756fd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-20T14:54:24+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1da2e172-78fb-417b-9417-1869bf49f838
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-23T09:15:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 99511f16-8cc5-4adc-8f9c-9f5456286d31 # Service Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35569ff0-67d7-43a1-a9f6-4f3ec49837be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e5f2023-3091-45e6-98ce-1e5832175bea
        userCondition: null
handle: blockHighlightedServices
hasTitleField: true
icon: gear
name: 'Block Highlighted Services'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
