color: violet
fieldLayouts:
  0d395430-11f8-4015-a0fb-3403364755e8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-09T14:22:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f59b8c85-f78a-4135-a5ec-0c9fab21749c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T14:25:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3d496bdf-f201-4f39-887e-7528c2f08f89 # Link Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0202ddee-5491-427f-be2d-45a9aa7302f0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7546265d-b816-4d2a-ae99-4e9a205a6757
        userCondition: null
handle: blockHighlightedLinks
hasTitleField: true
icon: link
name: 'Block Highlighted Links'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
