color: violet
fieldLayouts:
  4a94a05d-73eb-4657-b0ea-2347b4d6a90b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-09T14:22:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0344a04c-de2d-437e-8540-26b9afcf691a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-18T13:36:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c470466d-9f78-4cfb-a207-47323188907e # Abstract
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 224befae-bf77-414b-ac50-89e790e166c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-18T13:36:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce59acc5-38bc-446d-aa83-e31494f2d5c3 # HTML Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3777f989-f85c-4f6d-a372-8459b70bfe96
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-18T09:26:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 04af8e95-9178-465d-bdc8-a621ce7ff25c # Table
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63ea5102-ea63-46b7-bf62-8f4187259aba
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6fec7e66-895f-4b48-b15c-ded7b8539f65
        userCondition: null
handle: blockGenericTable
hasTitleField: true
icon: table
name: 'Block Generic Table'
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
