color: violet
fieldLayouts:
  49edff2a-dc25-4221-a7cb-6fc46f1a8d17:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-09T09:48:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 84842859-0ea3-4a89-89e2-198da554a5c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T09:51:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce59acc5-38bc-446d-aa83-e31494f2d5c3 # HTML Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1e5258d-3777-4db0-ab07-395e6d1c080d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T09:53:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2e315768-564c-4ee3-ba1c-711e11c1c0bb # Timeline Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a66a0151-a4de-45aa-b219-2dec05670006
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f7134a5e-13bd-4fe0-a634-fbf3ea80c4ee
        userCondition: null
handle: blockTimeline
hasTitleField: true
icon: list-timeline
name: 'Block Timeline'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
