color: violet
fieldLayouts:
  5a4d4dc8-9238-40b8-9e73-4f0019807b22:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-09T14:22:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f5a8f9b8-5602-43f6-8e9c-03fd66c02870
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-18T13:29:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c470466d-9f78-4cfb-a207-47323188907e # Abstract
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38212655-f552-4234-bea6-868491f630b0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-18T13:29:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce59acc5-38bc-446d-aa83-e31494f2d5c3 # HTML Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 251bcd9b-85e9-4946-829d-d2bc860c062e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-18T09:29:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 92bf6e7e-2d6b-431e-8fc0-f3b5edf5a18a # Attachment Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4952c327-b48c-45db-b52c-150128d991cc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eb1f1e9d-3576-49f8-ab16-e3653ace6c14
        userCondition: null
handle: blockAttachmentTable
hasTitleField: true
icon: link
name: 'Block Attachment Table'
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
