color: violet
fieldLayouts:
  40a97901-6a18-4c4c-99ea-296ca5f32940:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-09T14:22:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6207dd7f-f3fe-474a-915d-39ba30ef0256
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-18T13:42:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c470466d-9f78-4cfb-a207-47323188907e # Abstract
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 112a4fcd-7e6e-4546-8a4f-f5553542ef81
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-18T13:42:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce59acc5-38bc-446d-aa83-e31494f2d5c3 # HTML Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fe22bcc-c4da-4458-b906-9903ca0bb3fa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T14:25:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3d496bdf-f201-4f39-887e-7528c2f08f89 # Link Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 568318a2-4ee2-4fdf-b9b1-f6b05e9264a0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7039ef10-9e97-4266-83f7-16abcd2e7b4e
        userCondition: null
handle: blockListLinks
hasTitleField: true
icon: paperclip
name: 'Block List Links'
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
