color: green
fieldLayouts:
  010f4b4b-a4f2-4cf2-9bcf-f370954acc69:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-09T13:55:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6a02a281-4ccf-4aed-9c54-49c2e13206b5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T14:26:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5f8a7208-3d98-4188-a70f-56962a1fcb39 # Company Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1940c24-48c8-4666-81b0-48f1a7982391
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 26e31aea-e0f2-44ea-bd37-4230ef22eab7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-09T14:06:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6da9f8fe-2cfa-4562-b68b-cdc3af435bb4 # Meta Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c33e613a-0c8b-4785-a3b2-59d718d76dcf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T14:06:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2f5ad44b-f402-45cb-84c3-2b3e8f56c346 # Meta Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06820c78-8822-4020-ae6c-242074a48d23
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T14:06:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4cfa7a0a-c70c-48a4-a7d6-4992d0adbea2 # Og Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24c0c67d-65f2-4cef-8973-6735cb81e9ce
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 60ffdc12-82fc-4b47-bef0-0974d36b1f94
        userCondition: null
handle: company
hasTitleField: true
icon: building
name: Company
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
