color: blue
fieldLayouts:
  2d37a71e-d85d-4349-b771-0b1730383188:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-09T10:13:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 628efa69-2b3e-44f4-82dc-07d90dfa36ae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T13:19:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c470466d-9f78-4cfb-a207-47323188907e # Abstract
            handle: address
            includeInCards: false
            instructions: null
            label: Address
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f174b238-aab4-47a7-8dae-09a8f5d80607
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T10:16:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cee1eb13-8e85-4034-8a11-240f443b2c7e # Button Link
            handle: email
            includeInCards: false
            instructions: null
            label: Email
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a9d2b53-b023-49b1-ba0c-aa585e8431b2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 081daa7b-39f0-4fe9-af10-b2a4e482ff3a
        userCondition: null
handle: contactItem
hasTitleField: true
icon: address-book
name: 'Contact Item'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
