color: green
fieldLayouts:
  62406361-e403-424d-a133-25f7535b364e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-16T12:56:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a141318-fa1b-4f5a-87be-8bcd3131a60d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-16T12:58:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c470466d-9f78-4cfb-a207-47323188907e # Abstract
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a790f80f-5033-4ce8-80b0-5e5c82fca0c1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40373fc8-942c-4d62-9f2e-af76b59b2135
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-16T12:58:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6da9f8fe-2cfa-4562-b68b-cdc3af435bb4 # Meta Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2266db8-cf8a-4848-9880-ac0bf58b50c8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-16T12:58:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2f5ad44b-f402-45cb-84c3-2b3e8f56c346 # Meta Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c0e6f11-f23b-4392-8f6d-1950f4fd0324
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-16T12:58:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4cfa7a0a-c70c-48a4-a7d6-4992d0adbea2 # Og Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71c42a42-2650-4f66-a5d2-0d8affac0d29
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4d2895b1-a0b4-4d66-80d0-3ac924875837
        userCondition: null
handle: noticesIndex
hasTitleField: true
icon: trophy
name: 'Notices Index'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
