color: green
fieldLayouts:
  680c069d-dae1-4b1a-865b-37948e9042e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-09T13:56:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 82c2ccac-988d-41cf-ac13-93ee8519397f
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-05-15T14:22:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e1a68728-c41e-4c75-b77b-a703652d3524 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49b374db-35cb-40c5-8d99-1a6c86060047
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-15T14:22:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce59acc5-38bc-446d-aa83-e31494f2d5c3 # HTML Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20a66062-cc25-4e51-ba06-5816289ee17d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T13:58:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cee1eb13-8e85-4034-8a11-240f443b2c7e # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53cde8b6-7d9f-499d-bd7c-ed3d72b18fe3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T09:37:50+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: bf4d4e41-0123-44af-8c02-caa6724bb1e8
            userCondition: null
          -
            dateAdded: '2025-06-11T09:37:50+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Seleziona per vedere la tendina dei menù'
            type: craft\fieldlayoutelements\Tip
            uid: d2b23c06-052f-4a32-aa67-50c999470faa
            userCondition: null
          -
            dateAdded: '2025-06-11T09:32:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a414af45-eb1f-409e-b3bd-95e1f8db9485 # Boolean
            handle: withSidebar
            includeInCards: false
            instructions: null
            label: 'With Sidebar'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d81d064-70c2-4457-a442-afa9fb3f459c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T18:18:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4dc92844-360a-4d22-b405-e6332c22c613 # Text
            handle: sidebarTitle
            includeInCards: false
            instructions: null
            label: 'Sidebar Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7fea679-0f20-40d7-8d41-3719ee26c12c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-06-11T09:32:05+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: a414af45-eb1f-409e-b3bd-95e1f8db9485 # Boolean
                  layoutElementUid: 5d81d064-70c2-4457-a442-afa9fb3f459c
                  uid: a7ed8199-679f-48b5-96c5-67a4e671dce6
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 2a140bc3-24a8-4b4f-87cd-90efdd2dce3c # Navigation
            handle: sidebarNavigation
            includeInCards: false
            instructions: null
            label: 'Sidebar Navigation'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c59483c0-e2dd-487e-a563-9a57a381fd7b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-06-11T09:37:50+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 23e51b5d-ea67-4107-83aa-59c9b0b43dc5
            userCondition: null
          -
            dateAdded: '2025-05-09T13:58:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cced1acb-d051-4730-96ef-06483ba2f87e # Page Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e05e8bd2-c206-4f3d-a387-b56be146faa0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 96a80acb-0a35-4dee-9ee6-bee91570a212
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-09T14:09:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6da9f8fe-2cfa-4562-b68b-cdc3af435bb4 # Meta Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5acff9e7-10ef-4a7f-a035-1a7aa9d12f56
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T14:09:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2f5ad44b-f402-45cb-84c3-2b3e8f56c346 # Meta Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80fed700-d4eb-46f0-8f6b-819d906b838b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T14:09:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4cfa7a0a-c70c-48a4-a7d6-4992d0adbea2 # Og Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 459ebf56-1cc3-4852-82d6-a4c75891f63e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 2a3c40d1-f5a4-49bb-877f-95f00912ff6f
        userCondition: null
handle: pages
hasTitleField: true
icon: file
name: Pages
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
