color: green
fieldLayouts:
  7d45afd9-2d43-4e82-8d20-d8ab1fb15cee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-08T15:53:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 918785d7-a0b7-428f-b162-e4a61694a813
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-05-09T14:02:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da78d398-09aa-4396-bba7-eea929fbeef6 # Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 511214ef-8a34-4ad0-bb46-ae2d9fc08268
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-09T13:50:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: edd46841-59b8-493b-99cc-4c868dcb8b0f # Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39cdc18f-ceb1-45a1-96f0-f0d72ac3f569
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-08T15:59:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c470466d-9f78-4cfb-a207-47323188907e # Abstract
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ef7ab8c-f20a-4b04-9570-06d6ab127941
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T11:22:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ce59acc5-38bc-446d-aa83-e31494f2d5c3 # HTML Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a3f2b2c-263d-42e7-a836-805e61e38711
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T13:44:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cee1eb13-8e85-4034-8a11-240f443b2c7e # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81486ab9-996f-4cff-bbef-5f1221a44813
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-20T14:11:26+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 4b526843-08c6-4dd5-aa17-65944880d824
            userCondition: null
          -
            dateAdded: '2025-05-20T14:11:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a414af45-eb1f-409e-b3bd-95e1f8db9485 # Boolean
            handle: withSidebar
            includeInCards: false
            instructions: null
            label: 'With Sidebar'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecde0912-2636-4190-89ff-22bcbac218fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T13:44:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cced1acb-d051-4730-96ef-06483ba2f87e # Page Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5e7f393-6797-482e-af3c-0a6e286873ca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ebae865a-406c-421e-b1c8-f1b0fedb635f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-09T14:09:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6da9f8fe-2cfa-4562-b68b-cdc3af435bb4 # Meta Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 395fd828-2ef0-41de-810b-24b9db99eabd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T14:09:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2f5ad44b-f402-45cb-84c3-2b3e8f56c346 # Meta Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 085f750f-ceca-499a-b45b-626a6c69fb3c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T14:09:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4cfa7a0a-c70c-48a4-a7d6-4992d0adbea2 # Og Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 474cf56c-2c65-4679-acf2-3754dacbb4e9
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 6fc35623-bfd4-4475-8b48-4fe414242bd3
        userCondition: null
handle: pages
hasTitleField: true
icon: file-lines
name: Pages
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
