color: blue
fieldLayouts:
  bc32f577-1bb7-4382-9888-30d56030adc2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-23T09:11:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2236ab3d-860e-400a-9d4f-867aceb654cb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-23T09:14:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c470466d-9f78-4cfb-a207-47323188907e # Abstract
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91e240e0-afa1-4309-bde2-137d89b6cc9d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T13:48:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ec7b1c28-e91f-4648-8ad7-6f94b5f29358 # Service Entries
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8ae44e0-3270-456a-80f7-49bc3a525183
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-23T09:14:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cee1eb13-8e85-4034-8a11-240f443b2c7e # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f749405-41ed-4758-b2fa-1b3d61dc036f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 57224af8-8f2d-4f5b-acbf-c76641d11ae2
        userCondition: null
handle: servicesLauncher
hasTitleField: true
icon: gear
name: 'Services Launcher'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
