color: blue
fieldLayouts:
  82458232-7c61-4d13-a403-96605646c239:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-11T13:53:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 05bc742a-9f77-4e57-a356-31a320cd0f55
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T13:55:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cee1eb13-8e85-4034-8a11-240f443b2c7e # Button Link
            handle: link_
            includeInCards: false
            instructions: null
            label: Link
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 073346a3-a9ca-4988-a57b-d42182162c2f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ffce515-a713-4f44-99a8-f13c326916f3
        userCondition: null
handle: socialItem
hasTitleField: true
icon: thumbs-up
name: 'Social Item'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
