color: blue
fieldLayouts:
  54790801-dbc8-4828-8256-9516de578538:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-09T09:50:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d66ec3e1-0321-41fe-bdad-9005def94249
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-05-09T09:53:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da78d398-09aa-4396-bba7-eea929fbeef6 # Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a738bb5-dd2c-497e-aaf0-d66482519a26
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-09T09:53:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c470466d-9f78-4cfb-a207-47323188907e # Abstract
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 738302b7-1d84-4b92-af0f-90fc5df8889d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fc4f60ff-c024-4a48-9c8d-f465db55f101
        userCondition: null
handle: timelineItem
hasTitleField: true
icon: list-timeline
name: 'Timeline Item'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
