defaultPlacement: end
fieldLayouts:
  4def089a-8681-42f4-acfd-c545b2043d50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-13T08:32:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: e6d355ae-8b72-47e1-a29f-0e63a87b9bda
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T08:32:17+00:00'
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 9fe76d7a-f8d3-4d86-80cb-d50a4dccb795
            userCondition: null
            warning: null
          -
            attribute: newWindow
            dateAdded: '2025-05-13T08:32:17+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: ea560efb-3b15-4024-b803-c7b390c47b6e
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 608a48f6-94b2-433e-a92f-e41836fc32c5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-05-13T08:32:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 768ff461-0789-42d7-9978-235a0930dad2
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-05-13T08:32:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 420cb5eb-be94-4bde-a824-e6be6a4cbba5
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2025-05-13T08:32:17+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 2dbfe5c0-3481-4bcf-b309-9d1a5b99c397
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T14:27:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a414af45-eb1f-409e-b3bd-95e1f8db9485 # Boolean
            handle: secondary
            includeInCards: false
            instructions: null
            label: 'Secondary (Anchor Right)'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8da2d64-8e90-40ec-87d1-fe3eddb005a9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T14:27:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a414af45-eb1f-409e-b3bd-95e1f8db9485 # Boolean
            handle: buttonStyle
            includeInCards: false
            instructions: null
            label: 'Button Style'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc17aa3c-6154-4a02-9de9-a9cfd6b358b2
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: f32964e3-d5ae-4656-8162-edfe27099543
        userCondition: null
handle: mainNavigation
instructions: ''
maxNodes: null
name: 'Main Navigation'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  bf54d73b-d784-45ae-a6df-5d1677f128a5: # Italiano
    enabled: true
sortOrder: 1
structure:
  maxLevels: 1
  uid: 06bec295-995f-41e7-9639-ecef43bfa1b3
