columnSuffix: null
handle: boolean
instructions: null
name: Boolean
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
