columnSuffix: null
handle: columns
instructions: null
name: Columns
searchable: false
settings:
  defaultValue: 1
  max: 4
  min: 1
  step: 1
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
