columnSuffix: null
handle: column
instructions: null
name: Column
searchable: false
settings:
  customOptions: false
  iconsOnly: true
  options:
    -
      __assoc__:
        -
          - label
          - '1 / 4'
        -
          - value
          - col-lg-3
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '1 / 3'
        -
          - value
          - col-lg-4
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '1 / 2'
        -
          - value
          - col-lg-6
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3 / 4'
        -
          - value
          - col-lg-9
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2 / 3'
        -
          - value
          - col-lg-8
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Full
        -
          - value
          - col-12
        -
          - icon
          - ''
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
