columnSuffix: null
handle: companyBlocks
instructions: null
name: 'Company Blocks'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 8ceda25f-5419-417a-9fcd-9b0beb3c286e # Block Highlighted News
    -
      __assoc__:
        -
          - uid
          - abcb7aa6-b800-4473-8668-2a4b3addf4b4 # Block Highlighted Services
    -
      __assoc__:
        -
          - uid
          - 78a716d1-9d68-48ea-88d8-c47f47a1f3d1 # Block Highlighted Links
    -
      __assoc__:
        -
          - uid
          - 7c069235-fcc1-45ba-9106-c656ffc83ddb # Block Paragraph
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
