columnSuffix: null
handle: pageBlocks
instructions: null
name: 'Page Blocks'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 7c069235-fcc1-45ba-9106-c656ffc83ddb # Block Paragraph
    -
      __assoc__:
        -
          - uid
          - 6065cedf-8657-4bea-b1fe-6ca3fbcbda13 # Block Media
    -
      __assoc__:
        -
          - uid
          - 94019850-1257-45d7-ae9d-8553ae9caf62 # Block Timeline
    -
      __assoc__:
        -
          - uid
          - 41564f99-8920-4bfd-bd10-ba8f55b945c1 # Block Contacts
    -
      __assoc__:
        -
          - uid
          - 85f9e0fc-3b94-4966-9a82-5f3f2a24b602 # Block List Links
    -
      __assoc__:
        -
          - uid
          - 4b17b4fe-2617-46c6-946a-6c469a5468d5 # Block Attachment Table
    -
      __assoc__:
        -
          - uid
          - 1b39e3c3-7a01-4a65-8438-36649b1562d4 # Block Generic Table
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
