columnSuffix: null
handle: table
instructions: null
name: Table
searchable: false
settings:
  columnsAddRowLabel: null
  columnsInstructions: null
  columnsLabel: null
  enableAlignmentColumn: true
  enableWidthColumn: true
  rowsAddRowLabel: null
  rowsInstructions: null
  rowsLabel: null
translationKeyFormat: null
translationMethod: none
type: verbb\tablemaker\fields\TableMakerField
