fieldLayouts:
  269f5e78-ee83-4b49-9375-d47b6c5a2616:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-26T10:11:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4dc92844-360a-4d22-b405-e6332c22c613 # Text
            handle: companyName
            includeInCards: false
            instructions: null
            label: Name
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 853950a2-b4d6-4720-94f5-4d73f2815d5f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T09:15:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4f7b3632-82fe-4467-b89c-6db5c741b79b # Contact HTML
            handle: info
            includeInCards: false
            instructions: null
            label: Info
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9f47d9e-18f8-4d65-9c36-975ef8ea1351
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T09:15:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4f7b3632-82fe-4467-b89c-6db5c741b79b # Contact HTML
            handle: additionalInfo
            includeInCards: false
            instructions: null
            label: 'Additional Info'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 337f3c79-86e0-4025-98b6-2215f3ee3cbe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e7b68638-a535-4f57-be06-78e80278c01a
        userCondition: null
handle: companyInfo
name: 'Company Info'
sortOrder: 1
