fieldLayouts:
  269f5e78-ee83-4b49-9375-d47b6c5a2616:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-26T10:11:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4dc92844-360a-4d22-b405-e6332c22c613 # Text
            handle: companyName
            includeInCards: false
            instructions: null
            label: Name
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 853950a2-b4d6-4720-94f5-4d73f2815d5f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-26T10:11:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c470466d-9f78-4cfb-a207-47323188907e # Abstract
            handle: info
            includeInCards: false
            instructions: null
            label: Info
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e48feed-e7d8-4e85-8efe-d9413a3f0733
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-26T10:11:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c470466d-9f78-4cfb-a207-47323188907e # Abstract
            handle: additionalInfo
            includeInCards: false
            instructions: null
            label: 'Additional Info'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 466bfd67-ef58-48f1-82a2-233daa86c04e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e7b68638-a535-4f57-be06-78e80278c01a
        userCondition: null
handle: companyInfo
name: 'Company Info'
sortOrder: 1
