fieldLayouts:
  ff65e6f6-7c1f-4785-92ce-c75e51b99f83:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-11T13:55:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 52027cea-264e-4342-90c7-456eec3d29f1 # Social Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc5a60ce-80a9-48fc-96f3-7ba7be1d379f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85def17a-6153-4a8c-a8ff-46cfd65f5dd3
        userCondition: null
handle: socials
name: Socials
sortOrder: 3
