defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 17157e69-97f7-434e-b9ac-e173ed80c0eb # Notices Index
handle: noticesIndex
maxAuthors: 1
name: 'Pagina Lista Concorsi'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  bf54d73b-d784-45ae-a6df-5d1677f128a5: # Italiano
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: concorsi
type: single
