defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2b1527bd-6be5-4cea-bbe7-ff924ff583aa # Pages
handle: pages
maxAuthors: 1
name: Pagine
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  bf54d73b-d784-45ae-a6df-5d1677f128a5: # Italiano
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{slug}'
structure:
  maxLevels: 2
  uid: 92293c18-4fc3-4965-9a74-ab9de6512f95
type: structure
