defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5f41854c-a86a-48d4-9560-f6ec5bde1d66 # Transparencies
handle: transparenciesIndex
maxAuthors: 1
name: 'Indice Amministrazione Trasparente'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  bf54d73b-d784-45ae-a6df-5d1677f128a5: # Italiano
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: amministrazione-trasparente
type: single
