name: Craft Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug secrets availability
      run: |
        echo "Checking if secrets are available..."
        echo "HOST secret exists: ${{ secrets.HOST }}"
        echo "USERNAME secret exists: ${{ secrets.USERNAME }}"
        echo "SSH_KEY secret exists: ${{ secrets.SSH_KEY }}"
        echo "SSH_PASSPHRASE secret exists: ${{ secrets.SSH_PASSPHRASE }}"
        echo "PORT secret exists: ${{ secrets.PORT }}"

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}# Usa passphrase solo se necessaria
        passphrase: ${{ secrets.SSH_PASSPHRASE }}# Usa port solo se diverso da 22
        port: ${{ secrets.PORT || 22 }}# Aggiungi timeout e debug
        timeout: 60s
        command_timeout: 30m
        debug: true
        script: |
          echo "=== DEBUG: Connected successfully to server ==="
          whoami
          pwd
          echo "=== DEBUG: Checking if craftdemo directory exists ==="
          if [ -d "craftdemo" ]; then
            echo "Directory craftdemo exists"
            cd craftdemo
            pwd
            ls -la
          else
            echo "ERROR: Directory craftdemo does not exist"
            echo "Available directories:"
            ls -la
            exit 1
          fi
          echo "=== DEBUG: Checking git status ==="
          git status
          git remote -v
          echo "=== DEBUG: Pulling changes ==="
          git pull origin main
          echo "=== DEBUG: Checking composer ==="
          which composer
          composer --version
          echo "=== DEBUG: Updating dependencies ==="
          composer update --no-interaction --optimize-autoloader
          echo "=== DEBUG: Checking Craft CLI ==="
          which php
          php --version
          echo "=== DEBUG: Applying project config ==="
          php craft project-config/apply
