name: Craft Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug secrets availability
      run: |
        echo "Checking if secrets are available..."
        echo "HOST secret exists: ${{ secrets.HOST != '' }}"
        echo "USERNAME secret exists: ${{ secrets.USERNAME != '' }}"
        echo "SSH_KEY secret exists: ${{ secrets.SSH_KEY != '' }}"
        echo "SSH_PASSPHRASE secret exists: ${{ secrets.SSH_PASSPHRASE != '' }}"
        echo "PORT secret exists: ${{ secrets.PORT != '' }}"
  
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        debug: true
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd craftdemo # Cambia con il percorso del tuo sito
          
          # Pull delle modifiche dal repository
          git pull origin main
          
          # Installa/aggiorna le dipendenze
          composer update
          
          # Applica le configurazioni del progetto
          php craft project-config/apply
